name: Bug Report
description: Report a bug or issue with the Codocation
labels: ["bug"]
assignees: ["codocation"]

body:
  - type: input
    id: environment
    attributes:
      label: Codocation Version
      description: Required to reproduce the issue — the bug may already be fixed in a newer version
      placeholder: "2026.1"
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of Codocation is affected?
      multiple: true
      options:
        - Editor
        - Live Preview
        - TOC
        - Sources
        - ZIP Export
        - PDF Export
        - Settings
        - Localization
        - CLI
        - Welcome Screen
        - New Documentation Wizard
        - Other
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe the issue
      value: |
        **Description:**
        <!-- Please describe the issue you encountered -->

        **Steps to Reproduce:**
        1. 
        2. 
        3. 

        **Expected Result:**
        <!-- What did you expect to happen? -->

        **Actual Result:**
        <!-- What actually happened? -->

        **Screenshots / Screencast:**
        <!-- Drag and drop screenshots or screencast here -->
    validations:
      required: true

